apiVersion: v2
name: contosopos
description: A helm chart to deploy the Contoso Supermarket application
home: https://github.com/sebassem/jumpstart-agora-apps
type: application
version: 0.1.0
sources:
  - https://github.com/sebassem/jumpstart-agora-apps
