# Default values for flask-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ovmsURL: "ovms.contoso-motors.svc.cluster.local:8080"
influxdbURL: "http://influxdb.contoso-motors.svc.cluster.local:8086"
postRTSPURL: "virtual-rtsp-pose-svc.contoso-motors.svc.cluster.local:8554"
weldingRTSPURL: "virtual-rtsp-welding-svc.contoso-motors.svc.cluster.local:8554"
helmetRTSPURL: "virtual-rtsp-helmet-svc.contoso-motors.svc.cluster.local:8554"
objectRTSPURL: "virtual-rtsp-object-svc.contoso-motors.svc.cluster.local:8554"
boltRTSPURL: "virtual-rtsp-bolt-svc.contoso-motors.svc.cluster.local:8554"