apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensor-monitor.fullname" . }}-simulator
  labels:
    io.kompose.service: mqtt-simulator
  {{- include "sensor-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.simulator.replicas }}
  selector:
    matchLabels:
      io.kompose.service: mqtt-simulator
    {{- include "sensor-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        version: 1.0.14
        io.kompose.service: mqtt-simulator
      {{- include "sensor-monitor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.simulator.mqttSimulator.image.repository }}:{{ .Values.simulator.mqttSimulator.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.simulator.mqttSimulator.imagePullPolicy }}
        name: mqtt-simulator
        args: 
          - "--file"
          - "/jumpstart/settings.json"
        resources: {}
        volumeMounts:
        - name: mqtt-simulator-config-volume
          mountPath: /jumpstart
          readOnly: true

      volumes:
      - name: mqtt-simulator-config-volume
        configMap:
          name: mqtt-simulator-config

      imagePullSecrets:
      - name: charrisagoracr
      restartPolicy: Always