apiVersion: v2
name: contoso-motors
description: A Helm chart to deploy components for the Contoso Motors scenario
type: application
version: 0.1.2
appVersion: "1.16.1"
dependencies:
  - name: opcsimulator
    version: 0.1.0
    repository: "file://../opc-simulator"
  - name: ovms
    version: 0.1.0
    repository: "file://../ovms"
  - name: influxdb
    version: 0.1.0
    repository: "file://../influxdb"
  - name: mqtt
    version: 0.1.0
    repository: "file://../mqtt"
  - name: rtsp-simulator  
    version: 0.1.2
    repository: "file://../rtsp-simulator"
